---
- name: Install, Configure, and Sync Red Hat Satellite with RHEL 8, 9, and 10 Repos
  hosts: satellite_servers
  become: yes
  vars:
    organization: "L3_SOE"

  tasks:
  - name: Configure repo sets
    theforeman.foreman.repository_set:
      server_url: "https://{{ ansible_fqdn }}"
      username: "{{ admin_user }}"
      password: "{{ admin_password }}"
      validate_certs: no
      label: "rhel-9-for-x86_64-baseos-rpms"
      organization: "{{ organization }}"
      product: "Red Hat Enterprise Linux"
      repositories:
        - releasever: "9"
          basearch: "x86_64"
      state: enabled