---
- name: Configure Repo Sets
  hosts: satellite_servers

  vars:
    organization: "L3_SOE"
    repo_list:
      - name: "Red Hat Enterprise Linux 10 for x86_64 - BaseOS (RPMs)"
        version: 10
      - name: "Red Hat Enterprise Linux 10 for x86_64 - AppStream (RPMs)"
        version: 10
      - name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
        version: 9
      - name: "Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)"
        version: 9 

  tasks:
  - name: Configure repo sets
    ansible.builtin.command: hammer -u admin -p "{{ password }}" repository-set enable --name "{{ item.name }}" --organization "L3_SOE" --basearch "x86_64" --releasever "{{ item.version }}"
    loop: "{{ repo_list }}"
