---
- name: Query available repo sets
  hosts: satellite_servers
  become: yes
  vars:
    organization: "L3_SOE"

  tasks:
  - name: Configure repo sets
    redhat.satellite.repository_set_info:
      server_url: "https://{{ ansible_fqdn }}"
      username: "{{ admin_user }}"
      password: "{{ admin_password }}"
      validate_certs: no
      organization: "{{ organization }}"
      name: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)"
    register: output

  - name: repository output
    debug:
      var: output