---
- name: Create Satellite Manifest
  hosts: satellite_servers
  become: yes

  tasks:
    - name: Create satellite.example.com Manifest and add 7 sub
      redhat.satellite.redhat_manifest:
        uuid: "{{ uuid }}"
        username: "{{ username }}"
        password: "{{ password }}"
        path: /home/ec2-user/manifest.zip