---
- name: Create Satellite Manifest
  hosts: satellite_servers
  become: yes

  tasks:
     - name: Create satellite.example.com Manifest and add 7 sub
       theforeman.foreman.subscription_manifest:
         server_url: "{{ ansible_fqdn }}"
         username: "{{ admin_user }}"
         password: "{{ admin_password }}"
         organization: "L3_SOE"
         validate_certs: false  
         manifest_path: "{{ manifest_path }}"
         state: present